name: copy

on:
  workflow_dispatch:
  
  
  
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: git diff and set output
        id: set_output
        run: |
          $f="success"
          echo "test=$f" >> $GITHUB_OUTPUT
      - name: testing
        run: |
          echo "run the rest jobs = ${{ steps.set_output.outputs.test }}"
          


 
