name: copy

on:
  workflow_dispatch:
  
  
  
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - name: teettttt
        env:
          FINAL: ${{steps.step1.outputs.output1}}
        run: echo "$FINAL"
          
          


 
