name: copy

on:
  workflow_dispatch:
  
  
  
jobs:
  CreateVariableFile:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: store variable
        id: vars
        run: |
          $sol_name = "variable testing" 
           echo test="$sol_name" >> $GITHUB_ENV
      - name: fetch var
        run: |
          echo "${{ env.test}}"
        

