name: copy

on:
  workflow_dispatch:
  
  
  
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: git diff and set output
        id: set_output
        run: |
          $f="success"
          echo "TERMINUS_RELEASE=$f" >> $GITHUB_ENV

      - name: testing
        run: |
          echo $test
        env:
          test: ${{ env.TERMINUS_RELEASE }}

          
          


 
