name: copy

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      my_var:
        description: "The first output string"
        value: ${{jobs.my_job.outputs.my_var}}
jobs:
  my_job:
    # Map the job outputs to step outputs
    outputs:
      my_var: ${{steps.my_step.outputs.my_var}}
    steps:
    - name: Check out repo1
      uses: actions/checkout@v2
    - name: "Example output creation"
      id: "my_step"
      run: |
        my_var="Hello World"
        echo "Output [$my_var]"
        echo "my_var=$my_var" >> $GITHUB_OUTPUT 
    - name: tttt
      
