name: copy

on:
  workflow_dispatch:
  
  
  
jobs:
  job01:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: git diff and set output
        id: set_output
        run: |
          $f="success"
          write-output "TERMINUS_RELEASE=$f" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: ${{ steps.set_output.outputs.TERMINUS_RELEASE }}

      - name: testing
        run: |
          write-output "${{env.title}}"

          
          


 
