name: copy

on: [workflow_dispatch]
  
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: |
          write-output "testing code"
          echo test=hello >> $env:GITHUB_OUTPUT
      - id: step2
        run: echo test=world >> $env:GITHUB_OUTPUT
      - name: testing
        run: |
          write-output ${{steps.step1.outputs.test}}
  job2:
    runs-on: [windows-latest]
    outputs:
      out3: ${{ steps.step3.outputs.test3 }}
    needs: job1
    steps:
      - id: step3
        run: echo test3="world 3" >> $env:GITHUB_OUTPUT
      - name: testing step3
        run: |
          write-output ${{ steps.step3.outputs.test3 }}
          
