name: copy

on:
  workflow_dispatch:
  
  
  
jobs:
  job01:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: git diff and set output
        id: set_output
        run: |
          $f="success"
          echo "test=$f" >> $GITHUB_OUTPUT
      - name: testing
        run: |
          $tt=${{ steps.set_output.outputs.test }}
          $tt
          


 
