name: copy

on:
  workflow_dispatch:
  
  
  
jobs:
  CreateVariableFile:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: htlnxls/repo2
          token: ${{ secrets.ACC_KEY }}
