name: copyFilesfromRepo

on:
  workflow_dispatch:
  
  
defaults:
  run:
    shell: bash

jobs:
  CreateVariableFile:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout private actions
      uses: actions/checkout@v2
      with:
        repository: org/shared-private-actions
        path: .github/shared-actions
        token: ${{ secrets.Acc_key }}
