name: copyFilesfromRepo

on:
  workflow_dispatch:
  
  
defaults:
  run:
    shell: bash
env: 
  org: 'htlnxls'


jobs:
  CreateVariableFile:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout private actions
      uses: actions/checkout@v2
      with:
        repository: ${{ env.ROOT_PATH }}/repo2
        path: ./
        token: ${{ secrets.Acc_key }}
