name: flow1
#on: [push]

on: 
  workflow_dispatch:
    inputs:
      body:
        required: true
        type: string
env:
  repo: 'repo2'
 
jobs:
  flow1:
    runs-on: [windows-latest]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: update labels
        run: |
          gh workflow run flow2.yml --ref main --repo "tirupathirao027/${{env.repo}}" -f gggg="${{inputs.body}}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACC_KEY }}

