name: flow1
on: [push]

#on: [workflow_dispatch]
env:
  repo: 'tirupathirao027'
 
jobs:
  CreateResourceGroup:
    runs-on: [windows-latest]
    outputs:
      RESOURCE_Group_NAME: ${{ steps.getrg_details.outputs.rgsub_id }}   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: execute Azure devops pipeline API for RG
        id: getrg_details
        run: |
          echo rgsub_id="kkkkkkkk" >> $env:GITHUB_OUTPUT
  flow1:
    needs: CreateResourceGroup
    permissions:
      id-token: write
      contents: write
    uses: tirupathirao027/repo2/.github/workflows/flow2.yml@main
    with:
      gggg: ${{needs.CreateResourceGroup.outputs.RESOURCE_Group_NAME}}
    secrets: inherit
