name: flow1
#on: [push]

on: 
  workflow_dispatch:
    inputs:
      webapp_inputs:
        required: true
        type: string
env:
  VARFILE_PATH: '.\TEST'
 
jobs:
  flow1:
    runs-on: [windows-latest]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Create tfvar file
        run: |
          $json="$(${{inputs.webapp_inputs}}| ConvertTo-Json -Compress)"
          $req=$json|ConvertFrom-Json
          $subscriptionid=$req.subscriptionid
          $subscription_name=$req.subscription_name      
          $var_file_path = "${{ env.VARFILE_PATH }}\b1.auto.tfvars"
          write-output "$var_file_path"
          @"
          subscriptionid=$req.subscriptionid
          subscription_name=$req.subscription_name          
          "@ | Set-Content -Path "$var_file_path"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Add changes" -a
          git push

