name: flow1
on: [push]

#on: [workflow_dispatch]
env:
  repo: 'repo2'
 
jobs:
  CreateResourceGroup:
    runs-on: [windows-latest]
    outputs:
      RESOURCE_Group_NAME: ${{ steps.getrg_details.outputs.rgsub_id }}   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: execute Azure devops pipeline API for RG
        id: getrg_details
        run: |
          echo rgsub_id="kkkkkkkk" >> $env:GITHUB_OUTPUT
  flow1:
    needs: CreateResourceGroup
    runs-on: [windows-latest]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: update labels
        run: |
          gh workflow run flow2.yml --ref main --repo "tirupathirao027/${{env.repo}}" -f gggg=success
        env:
          GITHUB_TOKEN: ${{ secrets.ACC_KEY }}

