name: flow1
on: [push]

  #workflow_dispatch:
 
jobs:

  flow1:
    permissions:
      id-token: write
      contents: write
    uses: tirupathirao027/repo2/.github/workflows/flow2.yml@main
    with:
      gggg: "testttttttttttttttt"
    secrets: inherit
