name: CI 
on:
  workflow_dispatch:
 
jobs:

  build-and-test:
    permissions:
      id-token: write
      contents: read
    uses: tirupathirao027/repo2/.github/workflows/blank.yml@main
    secrets: inherit
