name: testCopyfile

#on: [push]

on:
  workflow_dispatch:
    inputs:
      body:
        required: true
        type: string        
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    steps:
      - name: test1
        id: test
        run: |
          write-output "${{inputs.test}}"
          $test="$(${{inputs.test}}| ConvertTo-Json -Compress)"
          $req=$test|ConvertFrom-Json
          $req.Account


