name: testCopyfile

#on: [push]

on:
  workflow_dispatch:
    inputs:
      body:
        required: true
        type: string        
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    steps:
      - name: test1
        id: get_snow_inputs
        run: |
          $json="$(${{inputs.body}}| ConvertTo-Json -Compress)"
          $req=$json|ConvertFrom-Json
          $requester_information=$req.requester_information
          $u_requester=$req.u_requester
          $userid=$req.userid
          $requester_location=$req.requester_location
          $phone=$req.phone
		      $SPECIAL_MSG=$req.SPECIAL_MSG_no_manager_exception_request_approver
          $opened_by=$req.opened_by
          $email=$req.email
          $office=$req.office
          $requester_asset_info=$req.requester_asset_info
          $iacpipelineid=$req.iacpipelineid
          $iacproject=$req.iacproject
          $iacbranchname=$req.iacbranchname
          $iacpipelinetimeout=$req.iacpipelinetimeout
          $iactimeoutag=$req.iactimeoutag
          $repo_admins=$req.repo_admins
          $repo_writers=$req.repo_writers
          $repo_readers=$req.repo_readers
          $tenant=$req.tenant
          $contributorupn=$req.contributorupn
          $team_name=$req.team_name
          $context_container=$req.name_context_container_start
          $solution_name=$req.solution_name
          $context=$req.context
          $DMZcheckbox=$req.DMZcheckbox
          $cost_center=$req.cost_center
          $financial_owner=$req.financial_owner
          $billing_contact=$req.billing_contact
          $department=$req.department
          $apm_id=$req.apm_id
          $market=$req.market
          $functional_owner=$req.functional_owner
          $technical_owner=$req.technical_owner
          $shared_cost=$req.shared_cost
          $data_classification=$req.data_classification
          $pii=$req.pii
          $network=$req.network
          $env_container=$req.environments_container_start
          $development=$req.development
          $test=$req.test
          $preproduction=$req.preproduction
          $production=$req.production
          $innovation=$req.innovation
          $integration=$req.integration
          $runtime=$req.runtime
          $sandbox=$req.sandbox
          $staging=$req.staging
          $exploration=$req.exploration
          $nonproduction=$req.nonproduction
          $env_container_end=$req.environments_container_end
          $acknow_container=$req.acknowledgement_container_start
          $spp_azure_region=$req.spp_azure_region
          $confirmation_gip=$req.confirmation_gip_azure_document
          $sub_rg_name=$req.view_subscription_resource_group_name
          $rg=$req.resource_group_name
          $repo_name=$req.repo_name
          $templates=$req.templates
          $region=$req.region
          $dxc_macro_template=$req.dxc_macro_template_16000
          $net_versions=$req.net_versions
          $php_versions=$req.php_versions
          $sku_tier=$req.sku_tier
          $Vcore=$req.total_number_of_vcores_for_elastic_pool
          $storage_max_size_in_gb=$req.storage_max_size_in_gb
          $ticket=$req.ticket
