name: testCopyfile

#on: [push]

on:
  workflow_dispatch:
    inputs:
      body:
        required: true
        type: string        
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    steps:
      - name: test1
        id: get_snow_inputs
        run: |
          $json="$(${{inputs.body}}| ConvertTo-Json -Compress)"
          $req=$json|ConvertFrom-Json
          $requester_information=$req.requester_information
          $u_requester=$req.u_requester
          $userid=$req.userid
          $requester_location=$req.requester_location
          $phone=$req.phone
          $SPECIAL_MSG=$req.SPECIAL_MSG_no_manager_exception_request_approver
          $opened_by=$req.opened_by
          $email=$req.email
          $office=$req.office
          $requester_asset_info=$req.requester_asset_info
          $iacpipelineid=$req.iacpipelineid
          $iacproject=$req.iacproject
          $iacbranchname=$req.iacbranchname
          $iacpipelinetimeout=$req.iacpipelinetimeout
          $iactimeoutag=$req.iactimeoutag
          $repo_admins=$req.repo_admins
          $repo_writers=$req.repo_writers
          $repo_readers=$req.repo_readers
          $tenant=$req.tenant
          $contributorupn=$req.contributorupn
          $team_name=$req.team_name
          $context_container=$req.name_context_container_start
          $solution_name=$req.solution_name
          $context=$req.context
          $DMZcheckbox=$req.DMZcheckbox
          $cost_center=$req.cost_center
          $financial_owner=$req.financial_owner
          $billing_contact=$req.billing_contact
          $department=$req.department
          $apm_id=$req.apm_id
          $market=$req.market
          $functional_owner=$req.functional_owner
          $technical_owner=$req.technical_owner
          $shared_cost=$req.shared_cost
          $data_classification=$req.data_classification
          $pii=$req.pii
          $network=$req.network
          $env_container=$req.environments_container_start
          $development=$req.development
          $test=$req.test
          $preproduction=$req.preproduction
          $production=$req.production
          $innovation=$req.innovation
          $integration=$req.integration
          $runtime=$req.runtime
          $sandbox=$req.sandbox
          $staging=$req.staging
          $exploration=$req.exploration
          $nonproduction=$req.nonproduction
          $env_container_end=$req.environments_container_end
          $acknow_container=$req.acknowledgement_container_start
          $spp_azure_region=$req.spp_azure_region
          $confirmation_gip=$req.confirmation_gip_azure_document
          $sub_rg_name=$req.view_subscription_resource_group_name
          $rg=$req.resource_group_name
          $repo_name=$req.repo_name
          $templates=$req.templates
          $region=$req.region
          $dxc_macro_template=$req.dxc_macro_template_16000
          $net_versions=$req.net_versions
          $php_versions=$req.php_versions
          $sku_tier=$req.sku_tier
          $Vcore=$req.total_number_of_vcores_for_elastic_pool
          $storage_max_size_in_gb=$req.storage_max_size_in_gb
          $ticket=$req.ticket
          echo requester_information=$requester_information >> $env:GITHUB_OUTPUT
          echo v=$u_requester >> $env:GITHUB_OUTPUT
          echo userid=$userid >> $env:GITHUB_OUTPUT
          echo requester_location=$requester_location >> $env:GITHUB_OUTPUT
          echo phone=$phone >> $env:GITHUB_OUTPUT
          echo SPECIAL_MSG=$SPECIAL_MSG >> $env:GITHUB_OUTPUT
          echo opened_by=$opened_by >> $env:GITHUB_OUTPUT
          echo email=$email >> $env:GITHUB_OUTPUT
          echo office=$office >> $env:GITHUB_OUTPUT
          echo requester_asset_info=$requester_asset_info >> $env:GITHUB_OUTPUT
          echo iacpipelineid=$iacpipelineid >> $env:GITHUB_OUTPUT
          echo iacproject=$iacproject >> $env:GITHUB_OUTPUT
          echo iacbranchname=$iacbranchname >> $env:GITHUB_OUTPUT
          echo iacpipelinetimeout=$iacpipelinetimeout >> $env:GITHUB_OUTPUT
          echo iactimeoutag=$iactimeoutag >> $env:GITHUB_OUTPUT
          echo repo_admins=$repo_admins >> $env:GITHUB_OUTPUT
          echo repo_writers=$repo_writers >> $env:GITHUB_OUTPUT
          echo repo_readers=$repo_readers >> $env:GITHUB_OUTPUT
          echo tenant=$tenant >> $env:GITHUB_OUTPUT
          echo contributorupn=$contributorupn >> $env:GITHUB_OUTPUT
          echo team_name=$team_name >> $env:GITHUB_OUTPUT
          echo context_container=$context_container >> $env:GITHUB_OUTPUT
          echo solution_name=$solution_name >> $env:GITHUB_OUTPUT
          echo context=$context >> $env:GITHUB_OUTPUT
          echo DMZcheckbox=$DMZcheckbox >> $env:GITHUB_OUTPUT
          echo cost_center=$cost_center >> $env:GITHUB_OUTPUT
          echo financial_owner=$financial_owner >> $env:GITHUB_OUTPUT
          echo billing_contact=$billing_contact >> $env:GITHUB_OUTPUT
          echo department=$department >> $env:GITHUB_OUTPUT
          echo apm_id=$apm_id >> $env:GITHUB_OUTPUT
          echo market=$market >> $env:GITHUB_OUTPUT
          echo functional_owner=$functional_owner >> $env:GITHUB_OUTPUT
          echo technical_owner=$technical_owner >> $env:GITHUB_OUTPUT
          echo shared_cost=$shared_cost >> $env:GITHUB_OUTPUT
          echo data_classification=$data_classification >> $env:GITHUB_OUTPUT
          echo pii=$pii >> $env:GITHUB_OUTPUT
          echo network=$network >> $env:GITHUB_OUTPUT
          echo env_container=$env_container >> $env:GITHUB_OUTPUT
          echo development=$development >> $env:GITHUB_OUTPUT
          echo test=$test >> $env:GITHUB_OUTPUT
          echo preproduction=$preproduction >> $env:GITHUB_OUTPUT
          echo production=$production >> $env:GITHUB_OUTPUT
          echo innovation=$innovation >> $env:GITHUB_OUTPUT
          echo integration=$integration >> $env:GITHUB_OUTPUT
          echo runtime=$runtime >> $env:GITHUB_OUTPUT
          echo sandbox=$sandbox >> $env:GITHUB_OUTPUT
          echo staging=$staging >> $env:GITHUB_OUTPUT
          echo exploration=$exploration >> $env:GITHUB_OUTPUT
          echo nonproduction=$nonproduction >> $env:GITHUB_OUTPUT
          echo env_container_end=$env_container_end >> $env:GITHUB_OUTPUT
          echo acknow_container=$acknow_container >> $env:GITHUB_OUTPUT
          echo spp_azure_region=$spp_azure_region >> $env:GITHUB_OUTPUT
          echo confirmation_gip=$confirmation_gip >> $env:GITHUB_OUTPUT
          echo sub_rg_name=$sub_rg_name >> $env:GITHUB_OUTPUT
          echo rg=$rg >> $env:GITHUB_OUTPUT
          echo repo_name=$repo_name >> $env:GITHUB_OUTPUT
          echo templates=$templates >> $env:GITHUB_OUTPUT
          echo region=$region >> $env:GITHUB_OUTPUT
          echo dxc_macro_template=$dxc_macro_template >> $env:GITHUB_OUTPUT
          echo net_versions=$net_versions >> $env:GITHUB_OUTPUT
          echo php_versions=$php_versions >> $env:GITHUB_OUTPUT
          echo sku_tier=$sku_tier >> $env:GITHUB_OUTPUT
          echo Vcore=$Vcore >> $env:GITHUB_OUTPUT
          echo storage_max_size_in_gb=$storage_max_size_in_gb >> $env:GITHUB_OUTPUT
          echo ticket=$ticket >> $env:GITHUB_OUTPUT
