name: testCopyfile

#on: [push]
on: 
  workflow_dispatch:

  
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    steps:
      - name: test1
        id: step1
        run: |
          write-output "${{ github.run_id }}"
          write-output " location => ${{inputs.location}}"
          write-output "sku  =>  ${{inputs.sku}}"
          
