name: testCopyfile

#on: [push]
on: [workflow_dispatch]
  
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    steps:
      - name: test1
        id: step1
        run: |
          $content = base64.encode(.\TEST\test1.txt)
          curl -i -X PUT -H ‘Authorization: Bearer token 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’ -d ‘{“message”: “uploading a sample pdf”, “content”:”$content”}’ https://api.github.com/repos/tirupathirao027/repo2/contents/sample.txt


          
