name: testCopyfile

on: [push]
  
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    steps:
      - name: te
        id: step1
        run: |
          curl -i -X PUT -H ‘Authorization: token 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’ -d ‘{“message”: “uploading a sample pdf”, “content”:”./TEST/test1.txt”}’ https://api.github.com/repos/tirupathirao027/repo2/contents/sample.txt


          
