name: testCopyfile

#on: [push]

on:
  workflow_dispatch:
    inputs:
      requester_information:
        required: true
        type: string          
      userid:
        required: true
        type: string                                  
      requester_location:
        required: true
        type: string                 
      phone:
        required: true
        type: string
      SPECIAL_MSG_no_manager_exception_request_approver:
        required: true
        type: string
      opened_by:
        required: true
        type: string  
      email:
        required: true
        type: string
      office:
        required: true
        type: string
      u_requester:
        required: true
        type: string
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    steps:
      - name: test1
        id: step1
        run: |
          write-output ${{inputs.requester_information}}
          write-output ${{inputs.u_requester}}
          write-output ${{inputs.userid}}
          write-output ${{inputs.requester_location}}
          write-output ${{inputs.phone}}
          write-output ${{inputs.SPECIAL_MSG_no_manager_exception_request_approver}}
          write-output ${{inputs.opened_by}}
          write-output ${{inputs.email}}
          write-output ${{inputs.office}}
