name: testCopyfile

#on: [push]

on:
  workflow_dispatch:
    inputs:
      test:
        required: true
        type: string        
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    steps:
      - name: test1
        id: test
        run: |
          write-output ${{inputs.test}}


