name: testCopyfile

#on: [push]

on:
  workflow_dispatch:
    inputs:
      requester_information:
        required: true
        type: string          
      userid:
        required: true
        type: string                                  
      requester_location:
        required: true
        type: string                 
      phone:
        required: true
        type: string
      SPECIAL_MSG_no_manager_exception_request_approver:
        required: true
        type: string
      opened_by:
        required: true
        type: string  
      email:
        required: true
        type: string
      office:
        required: true
        type: string
      requester_asset_info:
        required: true
        type: string
      iacpipelineid:
        required: true
        type: string
      iacproject:
        required: true
        type: string
      iacbranchname:
        required: true
        type: string
      iacpipelinetimeout:
        required: true
        type: string
      iactimeoutag:
        required: true
        type: string
      team_name:
        required: true
        type: string
      name_context_container_start:
        required: true
        type: string
      pii:
        required: true
        type: string
      environments_container_start:
        required: true
        type: string
      environments_container_end:
        required: true
        type: string
      acknowledgement_container_start:
        required: true
        type: string
      spp_azure_region:
        required: true
        type: string
      confirmation_gip_azure_document:
        required: true
        type: string
      view_subscription_resource_group_name:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      templates:
        required: true
        type: string
      dxc_macro_template_16000:
        required: true
        type: string
      total_number_of_vcores_for_elastic_pool:
        required: true
        type: string
      storage_max_size_in_gb:
        required: true
        type: string
      repo_admins:
        required: true
        type: string
      repo_writers:
        required: true
        type: string
      repo_readers:
        required: true
        type: string		
      location:
        required: true
        type: string
      region:
        required: true
        type: string		
      u_requester:
        required: true
        type: string
      market:
        required: true
        type: string		
      solution_name:
        required: true
        type: string		
      apm_id:
        required: true
        type: string		
      technical_owner:
        required: true
        type: string		
      financial_owner:
        required: true
        type: string		
      cost_center:
        required: true
        type: string		
      billing_contact:
        required: true
        type: string		
      context:
        required: true
        type: string		
      network:
        required: true
        type: string		
      shared_cost:
        required: true
        type: string		
      development:
        required: true
        type: string		
      test:
        required: true
        type: string		
      preproduction:
        required: true
        type: string		
      production:
        required: true
        type: string
      innovation:
        required: true
        type: string		
      integration:
        required: true
        type: string
      runtime:
        required: true
        type: string
      sandbox:
        required: true
        type: string
      staging:
        required: true
        type: string
      exploration:
        required: true
        type: string
      nonproduction:
        required: true
        type: string
      tenant:
        required: true
        type: string
      DMZcheckbox:
        required: true
        type: string
      contributorupn:
        required: true
        type: string
      department:
        required: true
        type: string
      ticket:
        required: true
        type: string
      data_classification:
        required: true
        type: string
      functional_owner:
        required: true
        type: string
      net_versions:
        required: true
        type: string
      php_versions:
        required: true
        type: string
      sku_tier:
        required: true
        type: string
  
  
  
jobs:
  job1:
    runs-on:  [windows-latest]
    steps:
      - name: test1
        id: step1
        run: |
          write-output ${{inputs.requester_information}}
          write-output ${{inputs.u_requester}}
          write-output ${{inputs.userid}}
          write-output ${{inputs.requester_location}}
          write-output ${{inputs.phone}}
          write-output ${{inputs.SPECIAL_MSG_no_manager_exception_request_approver}}
          write-output ${{inputs.opened_by}}
          write-output ${{inputs.email}}
          write-output ${{inputs.office}}
          write-output ${{inputs.requester_asset_info}}
          write-output ${{inputs.iacpipelineid}}
          write-output ${{inputs.iacproject}}
          write-output ${{inputs.iacbranchname}}
          write-output ${{inputs.iacpipelinetimeout}}
          write-output ${{inputs.iactimeoutag}}
          write-output ${{inputs.repo_admins}}
          write-output ${{inputs.repo_writers}}
          write-output ${{inputs.repo_readers}}
          write-output ${{inputs.tenant}}
          write-output ${{inputs.contributorupn}}
          write-output ${{inputs.team_name}}
          write-output ${{inputs.name_context_container_start}}
          write-output ${{inputs.solution_name}}
          write-output ${{inputs.context}}
          write-output ${{inputs.DMZcheckbox}}
          write-output ${{inputs.cost_center}}
          write-output ${{inputs.financial_owner}}
          write-output ${{inputs.billing_contact}}
          write-output ${{inputs.department}}
          write-output ${{inputs.apm_id}}
          write-output ${{inputs.market}}
          write-output ${{inputs.functional_owner}}
          write-output ${{inputs.technical_owner}}
          write-output ${{inputs.shared_cost}}
          write-output ${{inputs.data_classification}}
          write-output ${{inputs.pii}}
          write-output ${{inputs.network}}
          write-output ${{inputs.environments_container_start}}${{inputs.,
          write-output ${{inputs.development}}
          write-output ${{inputs.test}}
          write-output ${{inputs.preproduction}}
          write-output ${{inputs.production}}
          write-output ${{inputs.innovation}}
          write-output ${{inputs.integration}}
          write-output ${{inputs.runtime}}
          write-output ${{inputs.sandbox}}
          write-output ${{inputs.staging}}
          write-output ${{inputs.exploration}}
          write-output ${{inputs.nonproduction}}
          write-output ${{inputs.environments_container_end}}
          write-output ${{inputs.acknowledgement_container_start}}
          write-output ${{inputs.spp_azure_region}}
          write-output ${{inputs.confirmation_gip_azure_document${{inputs.
          write-output ${{inputs.view_subscription_resource_group_name}}
          write-output ${{inputs.resource_group_name${{inputs.estuseargp}}
          write-output ${{inputs.repo_name}}
          write-output ${{inputs.templates}}
          write-output ${{inputs.region}}
          write-output ${{inputs.dxc_macro_template_16000}}
          write-output ${{inputs.net_versions}}
          write-output ${{inputs.php_versions}}
          write-output ${{inputs.sku_tier}}
          write-output ${{inputs.total_number_of_vcores_for_elastic_pool}}
          write-output ${{inputs.storage_max_size_in_gb}}
          write-output ${{inputs.ticket}}
          
